### ISSUE TITLE
gitian: Debian 10 Virtualbox Host: lxc-net not populated

### ISSUE THREAD

**Issue by cryptapus** [bitcoin-core/docs#52]
Not sure if this is documented anywhere, but I had an issue with Debian 10 in that the targets seemed to not have routes. I found that Debian 10 (after an upgrade) doesn't appear to populate `/etc/default/lxc-net` by default, which should need the following:

    USE_LXC_BRIDGE="true"
    LXC_BRIDGE="br0"
    LXC_ADDR="10.0.3.1"
    LXC_NETMASK="255.255.255.0"
    LXC_NETWORK="10.0.3.0/24"
    LXC_DHCP_RANGE="10.0.3.2,10.0.3.254"
    LXC_DHCP_MAX="253"
    LXC_DHCP_CONFILE=""
    LXC_DOMAIN=""

Maybe this is useful if/when the docs are updated to the latest version of Debian for the VM.

**Comment by kristapsk** [comment]
I had the same problem with fresh Debian 10.7.0 install. Adding contents mentioned above to `/etc/default/lxc-net` solved the issue.

For the record, error message I got was:
```
lxc-execute: gitian: start.c: lxc_spawn: 1628 Failed to find gateway addresses
                                                                              lxc-execute: gitian: start.c: __lxc_start: 1951 Failed to spawn container "gitian"
                                                                                                                                                                lxc-execute: gitian: tools/lxc_execute.c: main: 245 Failed run an application inside container
Traceback (most recent call last):
        6: from bin/gbuild:332:in `<main>'
        5: from bin/gbuild:332:in `each'
        4: from bin/gbuild:334:in `block in <main>'
        3: from bin/gbuild:334:in `each'
        2: from bin/gbuild:339:in `block (2 levels) in <main>'
        1: from bin/gbuild:60:in `build_one_configuration'
bin/gbuild:23:in `system!': failed to run make-clean-vm --suite bionic --arch amd64 (RuntimeError)
Traceback (most recent call last):
  File "./gitian-build.py", line 262, in <module>
    main()
  File "./gitian-build.py", line 250, in main
    build()
  File "./gitian-build.py", line 63, in build
    subprocess.check_call(['bin/gbuild', '-j', args.jobs, '-m', args.memory, '--commit', 'bitcoin='+args.commit, '--url', 'bitcoin='+args.url, '../bitcoin/contrib/gitian-descriptors/gitian-linux.yml'])
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bin/gbuild', '-j', '2', '-m', '2000', '--commit', 'bitcoin=v0.21.0rc2', '--url', 'bitcoin=https://github.com/bitcoin/bitcoin', '../bitcoin/contrib/gitian-descriptors/gitian-linux.yml']' returned non-zero exit status 1.
```

**Comment by MarcoFalke** [comment]
Gitian has been archived and is no longer actively maintained for bitcoin-core, see #76
