### ISSUE TITLE
bin/gbuild:23:in `system!': failed to run on-target -u root apt-get update >> var/install.log 2>&1 (RuntimeError)

### ISSUE THREAD

**Issue by Giszmo** [bitcoin-core/docs#63]
I followed [this documentation](https://github.com/bitcoin-core/docs/blob/master/gitian-building.md), ran into issues as the VirtualBox instructions recommend debian 8, fixed those issues updating the VM to debian 10 and now fail building bitcoin/bitcoin.

I'm slightly confused by the whole stack with an LXC VM inside a VirtualBox VM and might be doing it wrong as I try to skip the "sign your results" part as I just try to get results for myself for now but here's the log:

```
$ ./gitian-build.py --detach-sign --no-commit -b satoshi 0.20.0
Cannot build for MacOS, SDK does not exist. Will build for other OSes
v0.20.0
HEAD is now at a62f0ed64 doc: Manpages update pre-final
Already up to date.

Building Dependencies

--2020-08-31 21:06:18--  https://github.com/mtrojnar/osslsigncode/archive/2.0.tar.gz
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/mtrojnar/osslsigncode/tar.gz/2.0 [following]
--2020-08-31 21:06:19--  https://codeload.github.com/mtrojnar/osslsigncode/tar.gz/2.0
Resolving codeload.github.com (codeload.github.com)... 140.82.114.10
Connecting to codeload.github.com (codeload.github.com)|140.82.114.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘inputs/osslsigncode-2.0.tar.gz’

inputs/osslsigncode-2.0.tar.gz                           [  <=>                                                                                                                 ]  56.59K   186KB/s    in 0.3s    

2020-08-31 21:06:20 (186 KB/s) - ‘inputs/osslsigncode-2.0.tar.gz’ saved [57951]

inputs/osslsigncode-2.0.tar.gz: OK
make: Entering directory '/home/gitianuser/bitcoin/depends'
make[1]: Entering directory '/home/gitianuser/bitcoin/depends'
make[1]: Leaving directory '/home/gitianuser/bitcoin/depends'
make[1]: Entering directory '/home/gitianuser/bitcoin/depends'
make[1]: Leaving directory '/home/gitianuser/bitcoin/depends'
make[1]: Entering directory '/home/gitianuser/bitcoin/depends'
make[1]: Leaving directory '/home/gitianuser/bitcoin/depends'
make: Leaving directory '/home/gitianuser/bitcoin/depends'

Compiling 0.20.0 Linux
--- Building for bionic amd64 ---
Stopping target if it is up
Making a new image copy
sudo: unable to resolve host gitian: Resource temporarily unavailable
Reading package lists... Done
Building dependency tree... Done
The following packages will be REMOVED:
  rsyslog*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 1466 kB disk space will be freed.
(Reading database ... 18583 files and directories currently installed.)
Removing rsyslog (8.32.0-1ubuntu4) ...
invoke-rc.d: could not determine current runlevel
 * Stopping enhanced syslogd rsyslogd
   ...done.
(Reading database ... 18525 files and directories currently installed.)
Purging configuration files for rsyslog (8.32.0-1ubuntu4) ...
dpkg: warning: while removing rsyslog, directory '/etc/apparmor.d/local' not empty so not removed
Processing triggers for systemd (237-3ubuntu10) ...
Adding 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
Adding 'local diversion of /usr/bin/ischroot to /usr/bin/ischroot.distrib'
Adding 'local diversion of /usr/sbin/policy-rc.d to /usr/sbin/policy-rc.d.distrib'
Starting target
Checking if target is up
Preparing build environment
Updating apt-get repository (log in var/install.log)
Traceback (most recent call last):
	6: from bin/gbuild:329:in `<main>'
	5: from bin/gbuild:329:in `each'
	4: from bin/gbuild:331:in `block in <main>'
	3: from bin/gbuild:331:in `each'
	2: from bin/gbuild:336:in `block (2 levels) in <main>'
	1: from bin/gbuild:117:in `build_one_configuration'
bin/gbuild:23:in `system!': failed to run on-target -u root apt-get update >> var/install.log 2>&1 (RuntimeError)
Traceback (most recent call last):
  File "./gitian-build.py", line 262, in <module>
    main()
  File "./gitian-build.py", line 250, in main
    build()
  File "./gitian-build.py", line 63, in build
    subprocess.check_call(['bin/gbuild', '-j', args.jobs, '-m', args.memory, '--commit', 'bitcoin='+args.commit, '--url', 'bitcoin='+args.url, '../bitcoin/contrib/gitian-descriptors/gitian-linux.yml'])
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bin/gbuild', '-j', '2', '-m', '2000', '--commit', 'bitcoin=v0.20.0', '--url', 'bitcoin=https://github.com/bitcoin/bitcoin', '../bitcoin/contrib/gitian-descriptors/gitian-linux.yml']' returned non-zero exit status 1.
```

**Comment by MarcoFalke** [comment]
Gitian has been archived and is no longer actively maintained for bitcoin-core, see #76
